# Site settings
baseurl = "http://bengudro.insomnia247.nl/"
languageCode = "en"
title = "BenGudro"
theme = "agency-bengudro"


[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.
	#
	# All icons using Fontawesome’s icon font.  Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons.  The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
	# information about you and your website.
	name = "BenGudro"
	description = "Web Programmer"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy.  The form makes a POST request to their servers to send the actual
	# email.  Visitors can send up to a 1000 email each month for free.
	#
	# What you need to do for the setup?
	#
	# - set your email address under ‘email’ below
	# - upload the generated site to your server
	# - send a dummy email yourself to confirm your account
	# - click the confirm link in the email from www.formspree.io
	# - you’re done.  Happy mailing!
	email = "benjamin.goudreault@gmail.com"


	# Navigation
	[params.navigation]
		brand = "BenGudro"
		#services = "Services"
		services = "Skills"
		portfolio = "Portfolio"
		about = "About"
		#team = "Team"
		team = "Me"
		contact = "Contact"


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace ‘header-bg.jpg’ in
		# the ‘static/img’ folder.
		title = "Welcome To My Page!"
		subtitle = "It’s nice to meet you"
		buttonText = "Cut to the chase"


	# Services section
#	[params.services]
#		title = "Services"
#		subtitle = "Lorem ipsum dolor sit amet consectetur."
#
#		[[params.services.list]]
#			icon = "fa-shopping-cart"
#			title = "E-Commerce"
#			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit.  Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
#
#		[[params.services.list]]
#			icon = "fa-laptop"
#			title = "Responsive Design"
#			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit.  Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."
#
#		[[params.services.list]]
#			icon = "fa-lock"
#			title = "Web"
#			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit.  Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."


	# Skills (Services) section
	[params.services]
		title = "Skills"
		subtitle = "A brief overview"

#		[[params.services.list]]
#			icon = "fa-shopping-cart"
#			title = "E-Commerce"
#			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit.  Minima maxime quam architecto quo inventore harum ex magni, dicta impedit."

		[[params.services.list]]
			icon = "fa-laptop"
			title = "Responsive Design"
			description = "Making sure web-pages look great on any device, from desktops to tablets to smartphones"

		[[params.services.list]]
			icon = "fa-lock"
			title = "Web"
			description = "When it comes to web standards, I like to do my research and get things right."

		[[params.services.list]]
			icon = "fa-wordpress"
			title = "Wordpress"
			description = "I can take care of your Wordpress installation & configuration, install themes, plugins, etc."

		[[params.services.list]]
			icon = "fa-html5"
			title = "HTML5"
			description = "I strive to make my html clean and valid."

		[[params.services.list]]
			icon = "fa-css3"
			title = "CSS3"
			description = "Because animations are fun."

		[[params.services.list]]
			icon = "fa-linux"
			title = "Linux"
			description = "Unafraid of the command-line, I use it every day, even on the weekend."


	# Portfolio section
	[params.portfolio]
		# All projects defined in their own files.  You can find example projects
		# at ‘examples/projects’.  Copy the ‘projects’ folder into the ‘data’ directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "Portfolio"
		subtitle = "Just a few samples of what I learned to do in school.<br />(Still under construction, more to come soon.)"

		[params.portfolio.modal]
			client = "Client"
			date = "Date"
			category = "Category"
			buttonText = "Close project"


	# About section
	[params.about]
		title = "About"
		subtitle = "What happened?"
		endpoint = "Let’s<br />work<br />together!"

		# The events will be listed from the top to the bottom
		# All images are stored under ‘static/img/about’.
		# Replace them with your own.
		[[params.about.events]]
			img = "1.jpg"
			date = "2013-2014"
			title = "My Humble Beginnings"
			description = "I studied web programming at Cégep de l’Outaouais in Hull, Québec, where I learned about tags and classes and objects and types and inheritance and recursion and all that wonderful stuff."

		[[params.about.events]]
			img = "2.jpg"
			date = "October 2014"
			title = "Going West"
			description = "The mountains were calling, and so was family."

		[[params.about.events]]
			img = "4.jpg"
			date = "Going forward"
			title = "Starting Afresh"
			description = "Now I’m trying to see if the skills I acquired in school can be put to good use in the web industry here in Western Canada."

#		[[params.about.events]]
#			img = "4.jpg"
#			date = "July 2014"
#			title = "Phase Two Expansion"
#			description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit.  Sunt ut voluptatum eius sapiente, totam reiciendis temporibus qui quibusdam, recusandae sit vero unde, sed, incidunt et ea quo dolore laudantium consectetur!"


	# Team section
	[params.team]
		title = "But who are you?"
		subtitle = "Here’s a pic.  Now you have no excuse not to say ‘hi’ next time you run into me."
		description = "I value family, community, and bringing people together.  That, and also quality coding and good design."

		# All team member pictures are stored under ‘static/img/team’.
		# Replace them with your own.
#		[[params.team.members]]
#			img = "1.jpg"
#			name = "Kay Garland"
#			position = "Lead Designer"
#			social = [
#				["fa-twitter", "#"],
#				["fa-facebook", "#"],
#				["fa-linkedin", "#"]
#			]
#
#		[[params.team.members]]
#			img = "2.jpg"
#			name = "Larry Parker"
#			position = "Lead Marketer"
#			social = [
#				["fa-twitter", "#"],
#				["fa-facebook", "#"],
#				["fa-linkedin", "#"]
#			]
#
#		[[params.team.members]]
#			img = "3.jpg"
#			name = "Diana Pertersen"
#			position = "Lead Developer"
#			social = [
#				["fa-twitter", "#"],
#				["fa-facebook", "#"],
#				["fa-linkedin", "#"]
#			]

		[[params.team.members]]
			img = "4.jpg"
			name = "Benjamin Goudreault"
			position = "This is me."
			social = [
				["fa-twitter", "https://twitter.com/bengudro/"],
				#["fa-facebook", "#"],
				["fa-linkedin", "https://www.linkedin.com/in/goudreault/"]
			]

	# Client section
	# All the clients’ logos are stored under ‘static/img/logos’.
	# Replace them with your clients’s logos.
	[[params.clients]]
		logo = "envato.jpg"
		link = "#"

	[[params.clients]]
		logo = "designmodo.jpg"
		link = "#"

	[[params.clients]]
		logo = "themeforest.jpg"
		link = "#"

	[[params.clients]]
		logo = "creative-market.jpg"
		link = "#"


	# Contact section
	[params.contact]
		title = "Get in touch"
#		subtitle = "Lorem ipsum dolor sit amet consectetur."
		buttonText = "Send message"

		# ‘warning’ defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
		copyright = "Published under the Apache License 2.0."

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "https://twitter.com/bengudro/"

#		[[params.footer.social]]
#			icon = "fa-facebook"
#			link = "#"

		[[params.footer.social]]
			icon = "fa-linkedin"
			link = "https://www.linkedin.com/in/goudreault/"

		[[params.footer.quicklinks]]
			text = "Privacy Policy"
			link = "#"

		[[params.footer.quicklinks]]
			text = "Terms of Use"
			link = "#"
